[package]
name = "calvin-staking"
version = "0.1.0"
description = "Calvin Staking Program - Manages CALVIN token staking and Vault Pass distribution"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "calvin_staking"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = { version = "0.31.1", features = ["init-if-needed"] }
anchor-spl = "0.31.1"
